### ISSUE TITLE
Not displaying 3 digit numbers

### ISSUE THREAD

**Issue by GCPins** [tuanbinhtran/voice-user-count#1]
When over 99 people are in the VC, the counter doesn't show the hundredths-place digit. 

![knepisci09a](https://user-images.githubusercontent.com/64855897/114413726-3e652c80-9b7c-11eb-983b-5501a06a6882.png)
![knepix9889a](https://user-images.githubusercontent.com/64855897/114413731-3efdc300-9b7c-11eb-870a-f62c323eeb6d.png)

For context, the VC is the only active one in the server right now, and definitely has more than 100 people connected. The user limit is set to "off"/infinite.

**Comment by tuanbinhtran** [comment]
@GCPins it's fixed now. thanks for reporting
