### ISSUE TITLE
[bug] Count shows on limited user channels with cameras active

### ISSUE THREAD

**Issue by pointydev** [tuanbinhtran/voice-user-count#2]
![](https://the.uwu.foundation/9aQYWX5.png)
Need I say more? ^

Thanks,
pointy

**Comment by tuanbinhtran** [comment]
Thanks for reporting, I'll look into it

**Comment by tuanbinhtran** [comment]
@pointydev 8e006c0fef158c16d4cd1fa6621b4d0dbe6a2466 It should be fixed now. 
Could you give it a test? Thanks

**Comment by pointydev** [comment]
![](https://the.uwu.foundation/617ioMK.png)
