### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by rollingmoai** [tuanbinhtran/voice-user-count#3]

**Comment by tuanbinhtran** [comment]
Thanks I'll look into it

**Comment by tuanbinhtran** [comment]
@itsmeboy0 It's now fixed d205dede3df25435760ad7fbe5f8cd6d8206df3e. 
Please tell me if it is working on your end.

**Comment by rollingmoai** [comment]
Thanks it works now. At first I was wondering why it wasn't updating but then I realized you changed the repo name (it was `pc-voice-user-count`). So I reinstalled the plugin.
