### ISSUE TITLE
No longer works (likely the canary update)

### ISSUE THREAD

**Issue by SheepCommander** [tuanbinhtran/voice-user-count#4]
![image](https://user-images.githubusercontent.com/66646514/148942091-0473f08e-a8da-4ca8-b3e1-a5d6bea1d1eb.png)

**Comment by tuanbinhtran** [comment]
Seems still to work here. 
The number won't show up if the channel is selected or hovered (just like the user limit indicator)

**Comment by SheepCommander** [comment]
Oh you're right, thanks 
![image](https://user-images.githubusercontent.com/66646514/149429228-fde6d491-0950-42d1-8f48-075b8fafff49.png)
